version: "3.8"
services:
  flask:
    build: .
    command: flask run --host 0.0.0.0
    environment:
        - FLASK_APP=hello.py
        - FLASK_ENV=development
    ports:
        - "5000:5000"
    volumes:
        - ./:/root
